name: LAMP Deployment

on:
    workflow_dispatch:
    push:
      branches:
      - main

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or vX.X.X version
        # optional (see below):
        with:
          targets: |
            ansible/playbook.yml
            ansible/inventory.yml

          args: "-c ansible/.ansible-lint"

      